### ISSUE TITLE
Do we require a library?

### ISSUE THREAD

**Issue by vkill** [LiveUI/VaporTestTools#2]
In this case, make application or request is easy. so, do we require a library?

```
import Vapor
import XCTest
@testable import App

final class YourTests: XCTestCase {
    func testFunc() throws {
        let req = try makeReq()
    }

    static let allTests = [
        ("testFunc", testFunc),
    ]

    func makeApp() throws -> Application {
        var config = Config.default()
        var env = try Environment.detect()
        var services = Services.default()

        try App.configure(&config, &env, &services)

        return try Application(
            config: config,
            environment: env,
            services: services
        )
    }

    func makeReq() throws -> Request {
        return Request(using: makeApp())
    }

}

```

**Comment by rafiki270** [comment]
Well, I guess not ... if you want to write the same repetitive code again and again and to have trouble when something changes because you won’t be able to make it work globally ... unless you make yourself a library, this moment I feel we have gone the full circle ...
Anyways, this library might not be for everyone and I will be happy to discuss any even the less constructive comments on Discord as `rafiki270`
